# Generated by Django 3.1.1 on 2020-09-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0002_course_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('duration', models.TimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.AlterField(
            model_name='university',
            name='courses',
            field=models.ManyToManyField(to='finder.Subjects'),
        ),
    ]
