# Generated by Django 3.1.1 on 2020-09-08 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0003_auto_20200908_1612'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subjects',
            new_name='Subject',
        ),
    ]
