# Generated by Django 3.1.1 on 2020-09-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0004_auto_20200908_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='duration',
        ),
        migrations.AddField(
            model_name='subject',
            name='image_src',
            field=models.URLField(blank=True),
        ),
    ]
